### ISSUE TITLE
Improve Readme

### ISSUE THREAD

**Issue by krish-bhanushali** [suraj1335/lazydo#2]
Improve Readme for a good open source Project.

**Comment by amanrubey** [comment]
Can I do it? Please assign me

**Comment by krish-bhanushali** [comment]
@amanrubey I am glad you want to contribute! I will be Improving basic Readme and then provide you references, you can then add your changes. I am assigning this to you now and will tell you soon so that you can start!.

**Comment by amanrubey** [comment]
Thanks for the response, but I want to apologise 😅
I'm really sorry for the inconvenience, 
Actually I was learning how to use Github and one of my friend was guiding me to use it and he forcefully made me make that comment. I am very new to Github and hence i don't have any idea about how to and what to write in readme 😅
I'm really sorry for my behaviour 😞
